version: '3.8'

services:
  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./backend/static:/usr/src/app/static:ro # :ro pour 'read-only' (sécurité)
    ports:
      - 9000:80
    depends_on:
      - frontend
  frontend:
   stdin_open: true
   build: ./frontend
   volumes:
    - ./frontend:/usr/src/app
    - /usr/src/app/node_modules
   expose:
    - 5173
   environment:
    - NODE_ENV=development
   depends_on:
    - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
  centrifugo:
    image: centrifugo/centrifugo:v6
    restart: unless-stopped
    volumes:
      - ./centrifugo:/centrifugo
    command: centrifugo -c config.json
    ports:
      - "8006:8007"

  db:
    image: postgres:15
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "grandchat"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=grandchat
      - POSTGRES_PASSWORD=grandchat
      - POSTGRES_DB=grandchat
    expose:
      - 5432
    ports:
      - 5432:5432
