version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "grandchat" ]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=grandchat
      - POSTGRES_PASSWORD=grandchat
      - POSTGRES_DB=grandchat
    expose:
      - 5432
    ports:
      - 5432:5432